spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/t1openschool
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: liquibase/changelog.yml
    enabled: true

server:
  port: 8080